// core.js の小さな確かめ
import fs from 'node:fs';
import vm from 'node:vm';
vm.runInThisContext(fs.readFileSync(new URL('../core.js', import.meta.url), 'utf8'));
const WC = globalThis.WC;
let fails = 0;
const ok = (c, m) => { console.log((c ? 'OK  ' : 'NG  ') + m); if (!c) fails++; };
ok(WC.fmt(999) === '999' && WC.fmt(1234) === '1.23K' && WC.fmt(1e36) === '1.00aa', '数字の書き方 ' + [WC.fmt(1234), WC.fmt(1e36), WC.fmt(1e39)]);
const s = WC.newState();
ok(s.wallHp === WC.hpFor(1), '最初の壁');
s.gold = 1e6;
const c10 = WC.upgCost(s, 'power', 10), sum = Array.from({ length: 10 }, (_, i) => { s.upg.power = i; return WC.upgCost(s, 'power', 1); }).reduce((a, b) => a + b);
s.upg.power = 0;
ok(Math.abs(c10 - sum) / sum < 1e-9, 'まとめ買いの値段 = 1 つずつの合計');
const n = WC.canBuyN(s, 'power', 'max');
ok(n > 0 && WC.upgCost(s, 'power', n) <= s.gold && WC.upgCost(s, 'power', n + 1) > s.gold, 'MAX で買える数 ' + n);
ok(WC.canBuyN(s, 'multi', 'max') <= 7, '上限つき');
const st = WC.stats(s);
let r = WC.damage(s, s.wallHp, st);
ok(r.broken && s.gold > 1e6, '壁が壊れて金貨');
WC.nextWall(s); ok(s.stage === 2 && s.runMax === 2, '次のステージ');
for (let i = 0; i < 40; i++) WC.tick(s, 1, WC.stats(s));
ok(!s.advance && s.stage === 1 && s.retry === 2, '時間切れで押し返される');
WC.retry(s); ok(s.advance && s.stage === 2, '再挑戦');
s.runMax = 40; const sh = WC.shardsFor(s);
ok(sh > 0, '転生で魂 ' + sh);
const ch = WC.abilityChoices(s, Math.random);
ok(ch.length === 3 && new Set(ch).size === 3, '選択肢 3 枚 ' + ch);
WC.doReset(s, ch[0]);
ok(s.resets === 1 && s.shards === sh && s.abil[ch[0]] === 1 && s.stage === 1 && s.upg.power === 0, '転生で強化が戻り能力が残る');
s.shards = 100; ok(WC.buy(s, 'p_dmg', 1) && WC.stats(s).dmgMult >= 2, '破壊のコア');
const fixed = WC.fix(JSON.parse(JSON.stringify({ ...s, upg: { power: 3 } })));
ok(fixed.upg.auto === 0 && fixed.upg.power === 3, '古いセーブを埋める');
console.log(fails ? `NG ${fails} 件` : 'すべて通過'); process.exit(fails ? 1 : 0);
